### ISSUE TITLE
Error 'datetime.datetime' object has no attribute 'split'

### ISSUE THREAD

**Issue by longzheng** [oziee/ha-solcast-solar#10]
I'm running the latest commit https://github.com/oziee/ha-solcast-solar/commit/06a974a1e41f6138c27bbaa7293e7ab439d5f59a

```
Logger: custom_components.solcast_solar
Source: custom_components/solcast_solar/__init__.py:301
Integration: Solcast PV Forecast (documentation, issues)
First occurred: 10:00:00 AM (16 occurrences)
Last logged: 11:00:00 AM

Traceback (most recent call last): File "/config/custom_components/solcast_solar/__init__.py", line 274, in update_data lastforecastdate = parse_datetime(lastforecast["period_end"]).replace(tzinfo=timezone.utc).astimezone(tz=None) File "/usr/local/lib/python3.9/site-packages/isodate/isodatetime.py", line 51, in parse_datetime datestring, timestring = datetimestring.split('T') AttributeError: 'datetime.datetime' object has no attribute 'split'
```

From full log
```
2021-10-11 11:00:00 WARNING (SyncWorker_6) [custom_components.solcast_solar] self.data is SOMETHING!!!!!

2021-10-11 11:00:00 ERROR (SyncWorker_6) [custom_components.solcast_solar] Traceback (most recent call last):
File "/config/custom_components/solcast_solar/__init__.py", line 274, in update_data
lastforecastdate = parse_datetime(lastforecast["period_end"]).replace(tzinfo=timezone.utc).astimezone(tz=None)
File "/usr/local/lib/python3.9/site-packages/isodate/isodatetime.py", line 51, in parse_datetime
datestring, timestring = datetimestring.split('T')
AttributeError: 'datetime.datetime' object has no attribute 'split'
```

**Comment by longzheng** [comment]
@oziee Sorry what do you mean?

It looks like line 274 https://github.com/oziee/ha-solcast-solar/blob/06a974a1e41f6138c27bbaa7293e7ab439d5f59a/custom_components/solcast_solar/__init__.py#L274

is the same as the error?
```
File "/config/custom_components/solcast_solar/__init__.py", line 274, in update_data
lastforecastdate = parse_datetime(lastforecast["period_end"]).replace(tzinfo=timezone.utc).astimezone(tz=None)
```

**Comment by B-Hartley** [comment]
I haven't got as far as logs yet. But latest commit doesn't work for me. Sensors show unknown. 
Switched back to previous version. Ok for now.

**Comment by oziee** [comment]
@B-Hartley yeah this current version is shit.. was trying to PR to HA and with all their needed ways to do things and its just caused too many problems

there are other problems where the ha listeners just are not updating ha so the data doesn't change on the screen

im looking into using the build in Recorder to be needed with this so that it can pull aging data for display and keep data for HA restarts

**Comment by wattmatters** [comment]
Well it fixed it for a day, but now it's broken again. Same errors.
