### ISSUE TITLE
Unexpected error importing solcast_solar/recorder.py - Solcast not polling

### ISSUE THREAD

**Issue by cakuhn** [oziee/ha-solcast-solar#122]
### The problem

Since yesterday, I am not able to poll information for Solcast.  Below is the full log:
I tried various times to reload, still not success.  Restored older versions of home assistant as well, but errors remain.  Please can you assist or guide me on what can potentially be the issue?

Logger: homeassistant.helpers.integration_platform
Source: loader.py:850
First occurred: 7:25:28 AM (5 occurrences)
Last logged: 7:26:05 AM

Unexpected error importing solcast_solar/recorder.py
Unexpected error importing solcast_solar/media_source.py
Unexpected error importing solcast_solar/logbook.py
Unexpected error importing solcast_solar/hardware.py
Unexpected error importing solcast_solar/cast.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 50, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.solcast.recorder'

### What version of Solcast Integration has the issue?

Unknown:  "Solcast API by Solcast Solar" only info available

### Diagnostics information

Logger: homeassistant.helpers.integration_platform
Source: loader.py:850
First occurred: 7:25:28 AM (5 occurrences)
Last logged: 7:26:05 AM

Unexpected error importing solcast_solar/recorder.py
Unexpected error importing solcast_solar/media_source.py
Unexpected error importing solcast_solar/logbook.py
Unexpected error importing solcast_solar/hardware.py
Unexpected error importing solcast_solar/cast.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 50, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.solcast.recorder'

### Logs debug/info/error output

```txt
Logger: homeassistant.helpers.integration_platform
Source: loader.py:850
First occurred: 7:25:28 AM (5 occurrences)
Last logged: 7:26:05 AM

Unexpected error importing solcast_solar/recorder.py
Unexpected error importing solcast_solar/media_source.py
Unexpected error importing solcast_solar/logbook.py
Unexpected error importing solcast_solar/hardware.py
Unexpected error importing solcast_solar/cast.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 50, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.solcast.recorder'
```

**Comment by oziee** [comment]
This is a new one
I have no idea why it's trying to even load any files by those names.
