### ISSUE TITLE
Integration no longer getting data

### ISSUE THREAD

**Issue by natbesh** [oziee/ha-solcast-solar#123]
### The problem

No longer receiving data from the API today.

- Reloaded the integration: still fails
- Changed the API key: still fails
- Deleted the integration & added it back: still fails

Error reported:
_Logger: custom_components.solcast_solar
Source: custom_components/solcast_solar/__init__.py:65
Integration: Solcast PV Forecast (documentation, issues)
First occurred: 09:21:48 (3 occurrences)
Last logged: 10:08:57

async_setup_entry: Traceback (most recent call last): File "/config/custom_components/solcast_solar/__init__.py",
 line 48, in async_setup_entry hass.config_entries.async_setup_platforms(entry, PLATFORMS) 
 AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'_

### What version of Solcast Integration has the issue?

New install 9th May (AU)

### What version of Home Assistant are you using?

Updated in the last 2 days to the latest

### Diagnostics information

Could be the api polling limits?

There's this line from the logs:
_ValueError: could not convert string to float: 'unavailable'_

### Logs debug/info/error output

```txt
2023-05-09 09:21:48.188 ERROR (MainThread) [custom_components.solcast_solar] async_setup_entry: Traceback (most recent call last):
  File "/config/custom_components/solcast_solar/__init__.py", line 48, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

2023-05-09 09:22:21.152 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ states('sensor.solar1_1_1min') | float + states('sensor.solar2_2_1min') | float }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1893, in forgiving_float_filter
    return float(value)
ValueError: could not convert string to float: 'unavailable'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 544, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2164, in _render_with_context
    return template.render(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1896, in forgiving_float_filter
    raise_no_default("float", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1594, in raise_no_default
    raise ValueError(
ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ states('sensor.solar1_1_1min') | float + states('sensor.solar2_2_1min') | float }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 665, in async_render_to_info
    render_info._result = self.async_render(variables, strict=strict, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 546, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ states('sensor.solar1_1_1min') | float + states('sensor.solar2_2_1min') | float }}' but no default was specified
2023-05-09 09:22:21.161 ERROR (MainThread) [homeassistant.helpers.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ states('sensor.solar1_1_1min') | float + states('sensor.solar2_2_1min') | float }}' but no default was specified') while processing template 'Template<template=({{ states('sensor.solar1_1_1min') | float + states('sensor.solar2_2_1min') | float }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.total_solar_m'
2023-05-09 09:22:38.823 ERROR (MainThread) [homeassistant.components.homeassistant_alerts] Timeout fetching homeassistant_alerts data

2023-05-09 10:05:15.220 ERROR (MainThread) [custom_components.solcast_solar] async_setup_entry: Traceback (most recent call last):
  File "/config/custom_components/solcast_solar/__init__.py", line 48, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

**Comment by oziee** [comment]
hi @natbesh 

I am not sure what version of the integration you have installed, but the `async_setup_platforms` was removed from this integration many version ago

version `3.0.46` is the latest version and does not include this code to cause the error you have

**Comment by natbesh** [comment]
Hi,
It was 3.0.30

Issue was that I was just re-adding it in integrations, I didnt go into HACS & do the upgrade there - so was just re-loading the old integration.

n00b HA person here, been a while since I was playing in the config.  Maybe add something in the doco - re:install process, remove from Integrations... remove from HACS & then xyz...?

Once updated in HACS all is working 100%.  Thankyou!!!
