### ISSUE TITLE
ERROR (MainThread) [custom_components.solcast_solar] sunrise_call_action: 

### ISSUE THREAD

**Issue by del13r** [oziee/ha-solcast-solar#15]
Hi,

I just updated to latest V2.0.4 and got this error.

**2021-11-02 09:35:41 ERROR (MainThread) [custom_components.solcast_solar] sunrise_call_action: Traceback (most recent call last):
File "/config/custom_components/solcast_solar/__init__.py", line 291, in sunrise_call_action
ac = int(ac)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'**

Full log for context

2021-11-02 09:35:40 DEBUG (MainThread) [custom_components.solcast_solar] Setting up Solcast for rooftop id XXXX-XXXX-XXXX-XXXX
2021-11-02 09:35:40 DEBUG (MainThread) [custom_components.solcast_solar] registering API limit reset
2021-11-02 09:35:40 DEBUG (MainThread) [custom_components.solcast_solar] registering daily forecast update at 00:00:00
2021-11-02 09:35:40 DEBUG (MainThread) [custom_components.solcast_solar] registered forecast_today sensor sensor.solcast_forecast_today
2021-11-02 09:35:40 DEBUG (MainThread) [custom_components.solcast_solar] registered forecast_today_remaining sensor sensor.solcast_forecast_today_remaining
2021-11-02 09:35:40 DEBUG (MainThread) [custom_components.solcast_solar] registered forecast_tomorrow sensor sensor.solcast_forecast_tomorrow
2021-11-02 09:35:40 DEBUG (MainThread) [custom_components.solcast_solar] registered API count sensor sensor.solcast_remaining_api_count
2021-11-02 09:35:40 DEBUG (MainThread) [custom_components.solcast_solar] registered last_update sensor sensor.solcast_last_updated
**2021-11-02 09:35:41 ERROR (MainThread) [custom_components.solcast_solar] sunrise_call_action: Traceback (most recent call last):
File "/config/custom_components/solcast_solar/__init__.py", line 291, in sunrise_call_action
ac = int(ac)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'**
2021-11-02 09:35:41 DEBUG (MainThread) [custom_components.solcast_solar] Updating Solcast estimated_actuals data
2021-11-02 09:35:41 DEBUG (MainThread) [custom_components.solcast_solar] Updated API count sensor
2021-11-02 09:35:41 DEBUG (MainThread) [custom_components.solcast_solar] Updated last_update (datetime) that successfully called Solcast API sensor
2021-11-02 09:35:41 DEBUG (MainThread) [custom_components.solcast_solar] Forecast successfully fetched and entity available
2021-11-02 09:35:43 DEBUG (MainThread) [custom_components.solcast_solar] Updated forecasts from Solcast API
2021-11-02 09:35:43 DEBUG (MainThread) [custom_components.solcast_solar] Notified 1 sensor listeners
2021-11-02 09:35:43 DEBUG (MainThread) [custom_components.solcast_solar] Notified 1 sensor listeners
2021-11-02 09:35:43 DEBUG (MainThread) [custom_components.solcast_solar] Notified 1 sensor listeners
2021-11-02 09:35:43 DEBUG (MainThread) [custom_components.solcast_solar] Notified 5 sensor listeners

**Comment by B-Hartley** [comment]
I'm seeing this too.......

2021-11-03 07:49:49 ERROR (MainThread) [custom_components.solcast_solar] sunrise_call_action: Traceback (most recent call last):
  File "/config/custom_components/solcast_solar/__init__.py", line 291, in sunrise_call_action
    ac = int(ac)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by jasonpstokes** [comment]
Yes known issue that is being worked on. A fix was tried as per #13 but isn't there yet.

**Comment by oziee** [comment]
let me know how v2.1.1 goes

**Comment by del13r** [comment]
2021-11-08 09:00:54 ERROR (MainThread) [custom_components.solcast_solar] async_remove_entry: Traceback (most recent call last):
File "/config/custom_components/solcast_solar/__init__.py", line 110, in async_remove_entry
coordinator: SolcastRooftopSite = hass.data[DOMAIN][entry.entry_id]
KeyError: 'solcast_solar'
2021-11-08 09:01:06 DEBUG (MainThread) [custom_components.solcast_solar] Setting up Solcast for rooftop id XXXX-XXXX-XXXX-XXXX
2021-11-08 09:01:06 DEBUG (MainThread) [custom_components.solcast_solar] DB id 37e9dab249eabb891c968f62fdb38350
2021-11-08 09:01:06 DEBUG (MainThread) [custom_components.solcast_solar] registering API limit reset
2021-11-08 09:01:06 DEBUG (MainThread) [custom_components.solcast_solar] registering API auto fetching hourly between sun up and sun set
2021-11-08 09:01:08 DEBUG (MainThread) [custom_components.solcast_solar] Updating Solcast estimated_actuals data
2021-11-08 09:01:08 DEBUG (MainThread) [custom_components.solcast_solar] Forecast successfully fetched and entity available
2021-11-08 09:01:08 DEBUG (MainThread) [custom_components.solcast_solar] Updated forecasts from Solcast API
2021-11-08 09:01:08 DEBUG (MainThread) [custom_components.solcast_solar] Update forecast service called for rooftop id XXXX-XXXX-XXXX-XXXX

**Comment by oziee** [comment]
I never tried the remove

Everything else working ok once you added the rooftop again?

**Comment by del13r** [comment]
I think we are good now.

![image](https://user-images.githubusercontent.com/86141523/140665459-e8ea91d9-596b-43be-b466-e4a04be00992.png)

![image](https://user-images.githubusercontent.com/86141523/140665470-b3ba05c3-bfb9-4a5d-a451-05411fab8b01.png)

**Comment by oziee** [comment]
Mine does the for some days.. other days it's more spot on.. it's just the data that is returned

**Comment by del13r** [comment]
I have ticked 
![image](https://user-images.githubusercontent.com/86141523/140679790-a92164ba-5b10-47f4-b8f3-2de7c15b84be.png)

but havent seen any updates all day
![image](https://user-images.githubusercontent.com/86141523/140679853-78f0e217-b1d8-426a-a432-23d01ab4d40d.png)

**Comment by jasonpstokes** [comment]
Me either :-(

![image](https://user-images.githubusercontent.com/29766924/140680584-c97b2338-2528-4138-a8f5-c80dc5d08924.png)

**Comment by oziee** [comment]
Me too on my production version of HA but my test version using older ha is ok.. hmm

@jasonpstokes yes service is gone.. only one would call if you had more than on integration setup
They are now "events" to call
![image](https://user-images.githubusercontent.com/1471841/140682316-b6a64d85-3a24-485a-bcdb-f0904aa4a057.jpeg)

**Comment by jasonpstokes** [comment]
Cheers. Firing the event updates the data, but the forecast vs remaining does not change:

![image](https://user-images.githubusercontent.com/29766924/140684611-0497f99b-5ecb-4079-a0ef-ffc8221d8d83.png)

...which has added a third hump to my forecast for today (from the previous versions forecast):
![image](https://user-images.githubusercontent.com/29766924/140684850-12f5e242-1c51-494e-abb0-fccebd95b1e7.png)


(It's currently 3:30pm - I WISH I could still generate 8kWh!)

**Comment by oziee** [comment]
> Cheers. Firing the event updates the data, but the forecast vs remaining does not change:

this might not be fixed in v2.1.2

humps.. you would have to look at the solecist toolkit graph, it would match

**Comment by oziee** [comment]
I think my data is updating every hour with remain kWh etc

Humps follow the actual data just like in the toolkit pages

My forecast in Ha
![image](https://user-images.githubusercontent.com/1471841/140843350-b966eaef-2439-4ce4-a298-d519189b8899.jpeg)

It's a combination of the two rooftop graphs 
![image](https://user-images.githubusercontent.com/1471841/140843389-90bd345f-9872-4cda-a898-d4a7666bc628.png)

**Comment by jasonpstokes** [comment]
Thanks @oziee, downloading 2.1.3 now. Really appreciate all your work on this!

**Comment by oziee** [comment]
@del13r the lag in the graph should be better in v.2.1.5
