### ISSUE TITLE
"Forecast Today" returns "Unknown"

### ISSUE THREAD

**Issue by pvprodk** [oziee/ha-solcast-solar#181]
### The problem

Did a fresh install yesterday after all the sensor naming change.
Every sensor works fine, except "Forecast Today":

![image](https://github.com/oziee/ha-solcast-solar/assets/79306514/7c39b1be-eaee-49c1-b01d-c6e33da7a0f7)

### What version of Solcast Integration has the issue?

v4.0.2

### What version of Home Assistant are you using?

 2023.8.3

### Logs debug/info/error output

```txt
This error originated from a custom integration.

Logger: custom_components.solcast_solar.sensor
Source: custom_components/solcast_solar/sensor.py:348
Integration: Solcast PV Forecast (documentation, issues)
First occurred: 3 September 2023 at 23:30:31 (35 occurrences)
Last logged: 09:51:07

SOLCAST - unable to get sensor value Incorrect number of forecasts returned. 0 Traceback (most recent call last): File "/config/custom_components/solcast_solar/sensor.py", line 344, in extra_state_attributes return self.coordinator.get_sensor_extra_attributes( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/coordinator.py", line 201, in get_sensor_extra_attributes return self.solcast.get_forecast_day(3) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/solcastapi.py", line 297, in get_forecast_day raise ValueError(f"Incorrect number of forecasts returned. {len(h)}") ValueError: Incorrect number of forecasts returned. 0
SOLCAST - unable to get sensor value Incorrect number of forecasts returned. 0 Traceback (most recent call last): File "/config/custom_components/solcast_solar/sensor.py", line 344, in extra_state_attributes return self.coordinator.get_sensor_extra_attributes( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/coordinator.py", line 203, in get_sensor_extra_attributes return self.solcast.get_forecast_day(4) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/solcastapi.py", line 297, in get_forecast_day raise ValueError(f"Incorrect number of forecasts returned. {len(h)}") ValueError: Incorrect number of forecasts returned. 0
SOLCAST - unable to get sensor value Incorrect number of forecasts returned. 0 Traceback (most recent call last): File "/config/custom_components/solcast_solar/sensor.py", line 344, in extra_state_attributes return self.coordinator.get_sensor_extra_attributes( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/coordinator.py", line 205, in get_sensor_extra_attributes return self.solcast.get_forecast_day(5) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/solcastapi.py", line 297, in get_forecast_day raise ValueError(f"Incorrect number of forecasts returned. {len(h)}") ValueError: Incorrect number of forecasts returned. 0
SOLCAST - unable to get sensor value Incorrect number of forecasts returned. 0 Traceback (most recent call last): File "/config/custom_components/solcast_solar/sensor.py", line 344, in extra_state_attributes return self.coordinator.get_sensor_extra_attributes( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/coordinator.py", line 207, in get_sensor_extra_attributes return self.solcast.get_forecast_day(6) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/solcastapi.py", line 297, in get_forecast_day raise ValueError(f"Incorrect number of forecasts returned. {len(h)}") ValueError: Incorrect number of forecasts returned. 0
SOLCAST - unable to get sensor value Incorrect number of forecasts returned. 38 Traceback (most recent call last): File "/config/custom_components/solcast_solar/sensor.py", line 344, in extra_state_attributes return self.coordinator.get_sensor_extra_attributes( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/coordinator.py", line 195, in get_sensor_extra_attributes return self.solcast.get_forecast_day(0) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/solcastapi.py", line 297, in get_forecast_day raise ValueError(f"Incorrect number of forecasts returned. {len(h)}") ValueError: Incorrect number of forecasts returned. 38


This error originated from a custom integration.

Logger: custom_components.solcast_solar.sensor
Source: custom_components/solcast_solar/sensor.py:254
Integration: Solcast PV Forecast (documentation, issues)
First occurred: 3 September 2023 at 23:28:09 (98 occurrences)
Last logged: 09:51:07

SOLCAST - unable to get sensor value Solcast data didn't return anything within 1:00:00 (needed_delta=23:59:59) Traceback (most recent call last): File "/config/custom_components/solcast_solar/sensor.py", line 305, in __init__ self._sensor_data = coordinator.get_sensor_value(entity_description.key) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/coordinator.py", line 166, in get_sensor_value return self.solcast.get_total_kwh_forecast_day(6) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/solcastapi.py", line 413, in get_total_kwh_forecast_day raise ValueError( ValueError: Solcast data didn't return anything within 1:00:00 (needed_delta=23:59:59)
SOLCAST - unable to get sensor value min() arg is an empty sequence Traceback (most recent call last): File "/config/custom_components/solcast_solar/sensor.py", line 305, in __init__ self._sensor_data = coordinator.get_sensor_value(entity_description.key) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/coordinator.py", line 168, in get_sensor_value return self.solcast.get_power_production_n_mins(0) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/solcastapi.py", line 325, in get_power_production_n_mins m = min( ^^^^ ValueError: min() arg is an empty sequence
SOLCAST - unable to get sensor value min() arg is an empty sequence Traceback (most recent call last): File "/config/custom_components/solcast_solar/sensor.py", line 305, in __init__ self._sensor_data = coordinator.get_sensor_value(entity_description.key) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/coordinator.py", line 170, in get_sensor_value return self.solcast.get_power_production_n_mins(30) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/solcastapi.py", line 325, in get_power_production_n_mins m = min( ^^^^ ValueError: min() arg is an empty sequence
SOLCAST - unable to get sensor value min() arg is an empty sequence Traceback (most recent call last): File "/config/custom_components/solcast_solar/sensor.py", line 305, in __init__ self._sensor_data = coordinator.get_sensor_value(entity_description.key) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/coordinator.py", line 172, in get_sensor_value return self.solcast.get_power_production_n_mins(60) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/solcastapi.py", line 325, in get_power_production_n_mins m = min( ^^^^ ValueError: min() arg is an empty sequence
SOLCAST - unable to get sensor value Solcast data didn't return anything within 1:00:00 (needed_delta=5:29:59) Traceback (most recent call last): File "/config/custom_components/solcast_solar/sensor.py", line 305, in __init__ self._sensor_data = coordinator.get_sensor_value(entity_description.key) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/coordinator.py", line 142, in get_sensor_value return self.solcast.get_total_kwh_forecast_day(0) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/solcastapi.py", line 413, in get_total_kwh_forecast_day raise ValueError( ValueError: Solcast data didn't return anything within 1:00:00 (needed_delta=5:29:59)
```

**Comment by pvprodk** [comment]
As a bonus information: I have two arrays configured, dont know if that affects anything, but it worked flawlessly in the previous version (3.X.X), and it also works for "tomorrow", D3-D7 etc..

**Comment by oziee** [comment]
yeah its a thing I see too.. but this is a copy of the already submitted issue #180

**Comment by oziee** [comment]
since the image is cut off.. by chance do you have a full image that shows at that exact time the api limit and count?

**Comment by pvprodk** [comment]
> since the image is cut off.. by chance do you have a full image that shows at that exact time the api limit and count?

Have s look at the Logbook. Last poll before this picture was 09:46 (UTC+2) with API count of 4 (so not limited)
