### ISSUE TITLE
Integration stopped working last week - ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by james474789** [oziee/ha-solcast-solar#196]
### The problem

Since last week the integration has stopped working. It doesnt appear to be making api calls to solcast and I dont understand why.

I have tried deleting/reinstalling the plugin. I have also reset my api key and confirmed this is good.

Log extract in the details section below.

### What version of Solcast Integration has the issue?

4.05

### What version of Home Assistant are you using?

2023.9.2

### Diagnostics information

[config_entry-solcast_solar-04baa0e3c6c61c4354a00d5c23e35591.json.txt](https://github.com/oziee/ha-solcast-solar/files/12617424/config_entry-solcast_solar-04baa0e3c6c61c4354a00d5c23e35591.json.txt)

### Logs debug/info/error output

```txt
2023-09-15 09:35:00.107 ERROR (MainThread) [custom_components.solcast_solar.sensor] SOLCAST - unable to get sensor value division by zero Traceback (most recent call last):
  File "/config/custom_components/solcast_solar/sensor.py", line 319, in _handle_coordinator_update
    self._sensor_data = self.coordinator.get_sensor_value(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solcast_solar/coordinator.py", line 75, in get_sensor_value
    return self.solcast.get_forecast_n_hour(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solcast_solar/solcastapi.py", line 330, in get_forecast_n_hour
    m = sum(z["pv_estimate"] for z in g) / len(g)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
ZeroDivisionError: division by zero

2023-09-15 09:35:00.115 ERROR (MainThread) [custom_components.solcast_solar.sensor] SOLCAST - unable to get sensor value division by zero Traceback (most recent call last):
  File "/config/custom_components/solcast_solar/sensor.py", line 319, in _handle_coordinator_update
    self._sensor_data = self.coordinator.get_sensor_value(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solcast_solar/coordinator.py", line 77, in get_sensor_value
    return self.solcast.get_forecast_n_hour(1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solcast_solar/solcastapi.py", line 330, in get_forecast_n_hour
    m = sum(z["pv_estimate"] for z in g) / len(g)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
ZeroDivisionError: division by zero

2023-09-15 09:35:00.128 ERROR (MainThread) [custom_components.solcast_solar.sensor] SOLCAST - unable to get sensor value max() arg is an empty sequence Traceback (most recent call last):
  File "/config/custom_components/solcast_solar/sensor.py", line 319, in _handle_coordinator_update
    self._sensor_data = self.coordinator.get_sensor_value(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solcast_solar/coordinator.py", line 105, in get_sensor_value
    return self.solcast.get_peak_w_day(1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solcast_solar/solcastapi.py", line 357, in get_peak_w_day
    m = max(z["pv_estimate"] for z in g)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() arg is an empty sequence

2023-09-15 09:35:00.133 ERROR (MainThread) [custom_components.solcast_solar.sensor] SOLCAST - unable to get sensor value max() arg is an empty sequence Traceback (most recent call last):
  File "/config/custom_components/solcast_solar/sensor.py", line 319, in _handle_coordinator_update
    self._sensor_data = self.coordinator.get_sensor_value(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solcast_solar/coordinator.py", line 107, in get_sensor_value
    return self.solcast.get_peak_w_time_day(1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solcast_solar/solcastapi.py", line 369, in get_peak_w_time_day
    return max((z for z in g), key=lambda x: x["pv_estimate"])["period_start"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() arg is an empty sequence
```

**Comment by oziee** [comment]
Says it right in the logs.. "divide by zero error" 😀 

It's a bug.. I'll fix that

**Comment by james474789** [comment]
Looks like something different has now cropped up:
2023-09-16 08:51:00.224 ERROR (MainThread) [custom_components.solcast_solar.coordinator] SOLCAST - update_integration_listeners: Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 525, in state
    if value.tzinfo is None:
       ^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'tzinfo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/solcast_solar/coordinator.py", line 50, in update_integration_listeners
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 173, in async_update_listeners
    update_callback()
  File "/config/custom_components/solcast_solar/sensor.py", line 327, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 730, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 830, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 771, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 536, in state
    raise ValueError(
ValueError: Invalid datetime: sensor.solcast_pv_forecast_peak_time_today has timestamp device class but provides state 0:<class 'int'> resulting in ''int' object has no attribute 'tzinfo''
[config_entry-solcast_solar-511e24f57ee8cec7fe271e45f009fd11.json.txt](https://github.com/oziee/ha-solcast-solar/files/12640131/config_entry-solcast_solar-511e24f57ee8cec7fe271e45f009fd11.json.txt)

**Comment by oziee** [comment]
I do know that Solcast was down this afternoon so that causes some problems..

but your major problem is that all your data is old and is missing the last few days of data as it last updated `"last_updated": "2023-09-07T08:37:47.542071+00:00",` and only has forecast data up to `2023-09-14T08:30:00+00:00`

its not going to fill in missing info.. if the next update doesn't help and get going again, you will have to delete the HA/config/solcast.json file and restart HA

**Comment by james474789** [comment]
Thanks, deleting solcast.json sorted it.
