### ISSUE TITLE
AttributeError: 'int' object has no attribute 'tzinfo'

### ISSUE THREAD

**Issue by james474789** [oziee/ha-solcast-solar#197]
### The problem

Thanks for issuing 4.0.6. I am now getting the following error

2023-09-16 08:51:00.224 ERROR (MainThread) [custom_components.solcast_solar.coordinator] SOLCAST - update_integration_listeners: Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 525, in state
    if value.tzinfo is None:
       ^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'tzinfo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/solcast_solar/coordinator.py", line 50, in update_integration_listeners
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 173, in async_update_listeners
    update_callback()
  File "/config/custom_components/solcast_solar/sensor.py", line 327, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 730, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 830, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 771, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 536, in state
    raise ValueError(
ValueError: Invalid datetime: sensor.solcast_pv_forecast_peak_time_today has timestamp device class but provides state 0:<class 'int'> resulting in ''int' object has no attribute 'tzinfo''

### What version of Solcast Integration has the issue?

4.0.6

### Diagnostics information

[config_entry-solcast_solar-511e24f57ee8cec7fe271e45f009fd11.json.txt](https://github.com/oziee/ha-solcast-solar/files/12640134/config_entry-solcast_solar-511e24f57ee8cec7fe271e45f009fd11.json.txt)

### Logs debug/info/error output

```txt
2023-09-16 08:51:00.224 ERROR (MainThread) [custom_components.solcast_solar.coordinator] SOLCAST - update_integration_listeners: Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 525, in state
    if value.tzinfo is None:
       ^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'tzinfo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/solcast_solar/coordinator.py", line 50, in update_integration_listeners
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 173, in async_update_listeners
    update_callback()
  File "/config/custom_components/solcast_solar/sensor.py", line 327, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 730, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 830, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 771, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 536, in state
    raise ValueError(
ValueError: Invalid datetime: sensor.solcast_pv_forecast_peak_time_today has timestamp device class but provides state 0:<class 'int'> resulting in ''int' object has no attribute 'tzinfo''
```

**Comment by oziee** [comment]
this was caused by Solcast being down today.. new update coming with better handling
