### ISSUE TITLE
Solcast integration doesn't load anymore after update to HA 2023.11.0b0

### ISSUE THREAD

**Issue by gieljnssns** [oziee/ha-solcast-solar#225]
### The problem

The integration doesn't load anymore after the update to the latest beta.

### What version of Solcast Integration has the issue?

v4.0.11

### What version of Home Assistant are you using?

core-2023.11.0b0

### Diagnostics information

[config_entry-solcast_solar-62ae80cc5b6e92d41be59aff19fc9674.json.txt](https://github.com/oziee/ha-solcast-solar/files/13172694/config_entry-solcast_solar-62ae80cc5b6e92d41be59aff19fc9674.json.txt)

### Logs debug/info/error output

```txt
2023-10-26 05:15:47.699 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform solcast_solar
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1021, in add_to_platform_finish
await self.async_internal_added_to_hass()
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 279, in async_internal_added_to_hass
raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.solcast_solaredge cannot be added as the entity category is set to config
2023-10-26 05:15:47.711 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up solcast_solar platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1021, in add_to_platform_finish
await self.async_internal_added_to_hass()
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 279, in async_internal_added_to_hass
raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.solcast_solaredge cannot be added as the entity category is set to config
```

**Comment by gieljnssns** [comment]
[config_entry-solcast_solar-62ae80cc5b6e92d41be59aff19fc9674.json](https://github.com/oziee/ha-solcast-solar/files/13172676/config_entry-solcast_solar-62ae80cc5b6e92d41be59aff19fc9674.json)

**Comment by oziee** [comment]
Where is "sensor.solcast_solaredge" coming from??

There isn't a sensor created with a name like that by default 

#And in the past ha betas have had internal errors that cause problems, that are internal bugs. That said until it's closer to release than a beta before I look too hard.. plus ha change things which can change more during betas

**Comment by gieljnssns** [comment]
I think I renamed those entities after the update to v4.x

**Comment by oziee** [comment]
HA betas are good to testing.. but they are buggy..

when it gets closer to release if the error is still there I will see it when I do some testing here.. but for now just stick with HA releases :)

**Comment by gieljnssns** [comment]
https://github.com/home-assistant/core/issues/102853

**Comment by gieljnssns** [comment]
@oziee 
I've investigated this a bit further.

It was only 2 sensors that no longer loaded
https://github.com/oziee/ha-solcast-solar/blob/43755c02bade337d143ab1c1f181c5c9a1dbdfe7/custom_components/solcast_solar/sensor.py#L232

If I change that line to `entity_category=EntityCategory.DIAGNOSTIC,`
It is all working again

**Comment by gieljnssns** [comment]
<img width="314" alt="Scherm­afbeelding 2023-10-26 om 18 44 27" src="https://github.com/oziee/ha-solcast-solar/assets/17234951/75f0d34c-a1ab-4ddc-b1ba-c1c12c602563">

**Comment by oziee** [comment]
yes I too searched around HA GitHub to see if anyone else was seeing beta problems.. but this new report came after I looked

and yes I knew that changing those lines would change its complaint

but this is NOT a problem with the solcast integration as its using the correct code 
https://github.com/home-assistant/core/blob/05fd64fe802b82a04888244e65e012611d8eb912/homeassistant/const.py#L1189

so this code is the same in HA for 2023.10 and still the same in 2023.11 beta

So as I said.. HA 2023.11 is a BETA and until release, nothing is going to change for this integration 

Use betas at your own risk of errors and bugs
