### ISSUE TITLE
Solcast sensor issue with 2023.11.b0

### ISSUE THREAD

**Issue by Thrasher2020** [oziee/ha-solcast-solar#226]
### The problem

Seeing this error witch I guess indicates an incorrect flag : 

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:367
Integration: Sensor (documentation, issues)
First occurred: 14:00:07 (1 occurrences)
Last logged: 14:00:07

Error while setting up solcast_solar platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1021, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 279, in async_internal_added_to_hass
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.hill_top_cottage cannot be added as the entity category is set to config

### What version of Solcast Integration has the issue?

v4.0.11

### What version of Home Assistant are you using?

2023.11.b0

### Logs debug/info/error output

```txt
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:367
Integration: Sensor (documentation, issues)
First occurred: 14:00:07 (1 occurrences)
Last logged: 14:00:07

Error while setting up solcast_solar platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1021, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 279, in async_internal_added_to_hass
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.hill_top_cottage cannot be added as the entity category is set to config
```

**Comment by gieljnssns** [comment]
https://github.com/oziee/ha-solcast-solar/issues/225#issuecomment-1781104127

**Comment by oziee** [comment]
Check before creating duplicate issues. #225 This has been reported already

It's a beta
