### ISSUE TITLE
Not getting values after update in my solcast account

### ISSUE THREAD

**Issue by w32-blaster** [oziee/ha-solcast-solar#259]
### The problem

I have added a second rooftop into my solcast account as a test then removed it after a few days. 
After the removal I don't get new values from the integration. 

I tried deleting the integration then re-add but still the same is happening. 
In HA log, I see this warning:
WARNING (MainThread) [homeassistant.components.rest.util] REST result could not be parsed as JSON

Also, when I removed the second rooftop but before I restarted HA, I saw the traceback pasted in the error output

### What version of Solcast Integration has the issue?

v4.0.14

### What version of Home Assistant are you using?

2023.12.4

### Logs debug/info/error output

```txt
2024-03-13 08:52:00.427 ERROR (MainThread) [custom_components.solcast_solar.sensor] SOLCAST - unable to get sensor value 'tally' Traceback (most recent call last):
  File "/config/custom_components/solcast_solar/sensor.py", line 424, in _handle_coordinator_update
    self._sensor_data = self.coordinator.get_site_sensor_value(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solcast_solar/coordinator.py", line 143, in get_site_sensor_value
    return self.solcast.get_rooftop_site_total_today(roof_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solcast_solar/solcastapi.py", line 282, in get_rooftop_site_total_today
    return self._data["siteinfo"][rooftopid]["tally"]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'tally'

2024-03-13 08:52:00.430 ERROR (MainThread) [custom_components.solcast_solar.sensor] SOLCAST - unable to get sensor value '0eb1-69fb-3a49-1ba4' Traceback (most recent call last):
  File "/config/custom_components/solcast_solar/sensor.py", line 424, in _handle_coordinator_update
    self._sensor_data = self.coordinator.get_site_sensor_value(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solcast_solar/coordinator.py", line 143, in get_site_sensor_value
    return self.solcast.get_rooftop_site_total_today(roof_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solcast_solar/solcastapi.py", line 282, in get_rooftop_site_total_today
    return self._data["siteinfo"][rooftopid]["tally"]
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: '0eb1-69fb-3a49-1ba4'
```

**Comment by oziee** [comment]
run the service "solcast_solar.clear_all_solcast_data"

**Comment by egolfer2523** [comment]
Had a similar issue. Running the service "solcast_solar.clear_all_solcast_data" and reloding the integration solved it.
