### ISSUE TITLE
Solcast Not working after update

### ISSUE THREAD

**Issue by Neomancer86** [oziee/ha-solcast-solar#296]
### The problem

Since updating to latest version solcast is not updating API data.

### What version of Solcast Integration has the issue?

v4.0.22

### What version of Home Assistant are you using?

2024.5.4

### Logs debug/info/error output

```txt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 723, in async_trigger
    return await self.action_script.async_run(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1731, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 503, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 533, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 501, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 736, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 699, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solcast_solar/__init__.py", line 139, in handle_service_update_forecast
    await coordinator.service_event_update()
  File "/config/custom_components/solcast_solar/coordinator.py", line 67, in service_event_update
    await self.solcast.http_data(dopast=False)
  File "/config/custom_components/solcast_solar/solcastapi.py", line 534, in http_data
    await self.http_data_call(site['resource_id'], site['apikey'], dopast)
  File "/config/custom_components/solcast_solar/solcastapi.py", line 591, in http_data_call
    raise TypeError(f"Solcast API did not return a json object. Returned {resp_dict}")
TypeError: Solcast API did not return a json object. Returned None
```

**Comment by Neomancer86** [comment]
note, not able to download diagnostics - I get a file not available on server

**Comment by Neomancer86** [comment]
AH, it seems API limits hit. must have hammered them when updating, the website said 7 API used but there must have been a lag

I made a second API and its working
