### ISSUE TITLE
V3.06 Causes Exceptions on startup

### ISSUE THREAD

**Issue by gedger** [oziee/ha-solcast-solar#46]
Upgraded component and rebooted.

Running 2022.6.4

```
This error originated from a custom integration.

Logger: custom_components.solcast_solar.solcastapi
Source: custom_components/solcast_solar/solcastapi.py:458 
Integration: Solcast PV Forecast (documentation, issues) 
First occurred: 09:58:29 (1 occurrences) 
Last logged: 09:58:29

Solcast http_data error: Traceback (most recent call last): File "/config/custom_components/solcast_solar/solcastapi.py", line 365, in http_data _data = _olddata['siteinfo'][site['resource_id']]['forecasts'] TypeError: 'float' object is not subscriptable

```
and

```
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:408 
Integration: Sensor (documentation, issues) 
First occurred: 09:58:29 (2 occurrences) 
Last logged: 09:58:29

Error adding entities for domain sensor with platform solcast_solar
Error while setting up solcast_solar platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 397, in state
    if value.tzinfo is None:
AttributeError: 'str' object has no attribute 'tzinfo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 408, in state
    raise ValueError(
ValueError: Invalid datetime: sensor.api_last_polled has a timestamp device class but does not provide a datetime state but <class 'str'>

```

and this on poll

```
This error originated from a custom integration.

Logger: custom_components.solcast_solar.coordinator
Source: custom_components/solcast_solar/coordinator.py:116 
Integration: Solcast PV Forecast (documentation, issues) 
First occurred: 10:00:10 (1 occurrences) 
Last logged: 10:00:10

update_forecast: Traceback (most recent call last): File "/config/custom_components/solcast_solar/coordinator.py", line 84, in update_forecast if last_update < date_now: TypeError: '<' not supported between instances of 'str' and 'datetime.datetime'

```

**Comment by oziee** [comment]
Try deleting the "solcast.json" file in the config directory in HA and restart Ha and see if it then works??

**Comment by gedger** [comment]
Beat me to it I was just about to report back that deleting the solcast.json file and restarting has fixed the issue.

**Comment by oziee** [comment]
Yeah the json file keys changed and make some changes

**Comment by gedger** [comment]
Not sure whether it's possible to embed a version number in the json file and auto delete it if it doesn't match, I can see this catching a few people out, otherwise looks great so far.

**Comment by oziee** [comment]
As long as nothing changes now it won't matter in the future

I like to think of it as "beta".. things change and problems happen :)

But really I don't come across these problems mostly because in my coding and use I delete and change things as it goes.. it you poor users that suffer the changes :)

Hinge sight I could make it fool proof, but never think about that. There are other ways than a version number in the file to make it delete. Hopefully from now on nothing changes and it's bug free when freshly installed:)
