### ISSUE TITLE
After update last version  value = 0i

### ISSUE THREAD

**Issue by seblang** [oziee/ha-solcast-solar#47]
I have juste update to the last version but all value are yet to zero

**Comment by oziee** [comment]
What version u upgrade from v2 or v3?

**Comment by seblang** [comment]
V.3.0. 6

**Comment by esponjaman** [comment]
Have a bug in 3.0.6, also 0 in every valor.

`Logger: homeassistant
Source: components/sensor/__init__.py:408
First occurred: 14:30:01 (3 occurrences)
Last logged: 16:30:01

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 397, in state
    if value.tzinfo is None:
AttributeError: 'str' object has no attribute 'tzinfo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/solcast_solar/coordinator.py", line 122, in service_event_update
    update_callback()
  File "/config/custom_components/solcast_solar/sensor.py", line 197, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 408, in state
    raise ValueError(
ValueError: Invalid datetime: sensor.api_last_polled has a timestamp device class but does not provide a datetime state but <class 'str'>
```
Logger: homeassistant
Source: components/sensor/__init__.py:408
First occurred: 14:30:01 (3 occurrences)
Last logged: 16:30:01

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 397, in state
    if value.tzinfo is None:
AttributeError: 'str' object has no attribute 'tzinfo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/solcast_solar/coordinator.py", line 122, in service_event_update
    update_callback()
  File "/config/custom_components/solcast_solar/sensor.py", line 197, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 408, in state
    raise ValueError(
ValueError: Invalid datetime: sensor.api_last_polled has a timestamp device class but does not provide a datetime state but <class 'str'>
```
`

**Comment by oziee** [comment]
Make sure to delete the HA-config-solcast.json file and restart HA

**Comment by esponjaman** [comment]
> Make sure to delete the HA-config-solcast.json file and restart HA

That did the trick, for me this issue is closed.
Maybe put this hint in the change log, so others can be aware of this step.
Thanks for the fast reply and solution.
