### ISSUE TITLE
Errors installing in HA 2022.7.2

### ISSUE THREAD

**Issue by reddog-42** [oziee/ha-solcast-solar#59]
I tried to install on 2022.6 but it wouldn't let me. 

I have a new account (few days) with solcast, and have added two sites, for two orientations. One API key.

I installed successfully on 2022.7.0 Seemed to start ok and I got at least one forecast, but it stopped working.
I deleted, re downloaded and reinstalled on 2022.7.2 and set logging to debug.

I am getting the following errors in log:

2022-07-09 14:42:10 DEBUG (MainThread) [custom_components.solcast_solar.coordinator] Solcast - Registering API auto fetching hourly between sun up and sun set
2022-07-09 14:42:10 DEBUG (MainThread) [custom_components.solcast_solar.coordinator] Solcast - API will only connect between the hours 6 and 18 and at midnight
2022-07-09 14:42:10 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Solcast polling for data
2022-07-09 14:42:10 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Solcast including past actual data? - False
2022-07-09 14:42:10 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Solcast api polling for rooftop 2231-256e-8212-dd80
2022-07-09 14:42:10 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Solcast api polling for rooftop 9c7a-9b92-80f5-a3fc
2022-07-09 14:42:10 ERROR (MainThread) [custom_components.solcast_solar.solcastapi] Solcast http_data error: Traceback (most recent call last):
File "/config/custom_components/solcast_solar/solcastapi.py", line 369, in http_data
_data = _olddata['siteinfo'][site['resource_id']]['forecasts']
KeyError: '9c7a-9b92-80f5-a3fc'
2022-07-09 14:42:10 DEBUG (MainThread) [custom_components.solcast_solar.coordinator] Finished fetching solcast_solar data in 0.467 seconds (success: True)
2022-07-09 14:42:10 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform solcast_solar
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 397, in state
if value.tzinfo is None:
AttributeError: 'str' object has no attribute 'tzinfo'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 397, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 641, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
state = self._stringify_state(available)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
if (state := self.state) is None:
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 408, in state
raise ValueError(
ValueError: Invalid datetime: sensor.solcast_api_last_polled has timestamp device class but provides state 2000-01-01T04:42:10.845632+00:00:<class 'str'> resulting in ''str' object has no attribute 'tzinfo''
2022-07-09 14:42:10 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up solcast_solar platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 397, in state
if value.tzinfo is None:
AttributeError: 'str' object has no attribute 'tzinfo'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 258, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 397, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 641, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
state = self._stringify_state(available)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
if (state := self.state) is None:
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 408, in state
raise ValueError(
ValueError: Invalid datetime: sensor.solcast_api_last_polled has timestamp device class but provides state 2000-01-01T04:42:10.845632+00:00:<class 'str'> resulting in ''str' object has no attribute 'tzinfo''

**Comment by oziee** [comment]
not sure what has happened.. 

first delete the HA>config>solcast.json file and restart HA

**Comment by reddog-42** [comment]
Thank you.
Running after json delete and HA restart. No errors in log, and a graph in Energy dashboard.
